jobs:

- job: unix
  displayName: Unix
  strategy:
    matrix:
      macos:
        vmImage: macOS-12
        install: brew install
      ubuntu:
        vmImage: ubuntu-22.04
        install: sudo apt install -y
  pool:
    vmImage: $(vmImage)
  steps:
  - task: UseDotNet@2
    displayName: Use .NET 6
    inputs: { version: 6.x }
  - script: $(install) bmake
    displayName: Install packages
  - script: bmake
    displayName: Build

- job: vs
  displayName: "Visual Studio"
  strategy:
    matrix:
      x86: { platform: x86 }
      x64: { platform: x64 }
      arm: { platform: ARM }
  pool:
    vmImage: windows-2022
  steps:
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: aoc.sln
      platform: $(platform)
      configuration: Release

- job: vc6
  displayName: "Visual C++ 6"
  continueOnError: true
  pool:
    name: default
    demands: vc6
  steps:
  - script: cd 2020\c\vc6 & msdev aoc2020.dsw /make all release
    displayName: Build 2020
  - script: cd 2022\c\vc6 & msdev aoc2022.dsw /make all release
    displayName: Build 2022
