jobs:

- job: linux
  displayName: Linux
  pool:
    vmImage: ubuntu-20.04
  steps:
  - task: UseDotNet@2
    displayName: Use .NET 6
    inputs:
      version: 6.x
  - script: sudo apt install -y bmake
    displayName: Install packages
  - script: bmake
    displayName: Build

- job: macos
  displayName: macOS
  pool:
    vmImage: macOS-12
  steps:
  - task: UseDotNet@2
    displayName: Use .NET 6
    inputs:
      version: 6.x
  - script: brew install bmake
    displayName: Install packages
  - script: bmake
    displayName: Build

- job: vs
  displayName: "Visual Studio"
  strategy:
    matrix:
      x86: { platform: x86 }
      x64: { platform: x64 }
      arm: { platform: ARM }
  pool:
    vmImage: windows-2019
  steps:
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: aoc.sln
      platform: $(platform)
      configuration: Release

- job: vc6
  displayName: "Visual C++ 6"
  continueOnError: true
  pool:
    name: default
    demands: vc6
  steps:
  - script: cd 2020\c\vc6 & msdev aoc2020.dsw /make all release
    displayName: Build 2020
  - script: cd 2022\c\vc6 & msdev aoc2022.dsw /make all release
    displayName: Build 2022

- job: vs_dotnet
  displayName: "2021: Windows (dotnet)"
  pool:
    vmImage: windows-2019
  steps:
  - task: UseDotNet@2
    displayName: Use .NET 6
    inputs:
      version: 6.x
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      workingDirectory: 2021/cs
      arguments: -c Release
