jobs:

- job: linux
  displayName: Linux
  strategy:
    matrix:
      ubuntu-2004: { host: ubuntu-20.04 }
      ubuntu-2404: { host: ubuntu-24.04 }
  pool:
    vmImage: $(host)
  steps:
  - task: UseDotNet@2
    inputs: { version: 6.x }
  - script: sudo apt install -y bmake mono-devel
    displayName: Install packages
  - script: bmake -j $(nproc)
    displayName: Build

- job: macos
  displayName: macOS
  pool:
    vmImage: macOS-14  # no ARM agent on Azure yet
  steps:
  - task: UseDotNet@2
    displayName: Use .NET 6
    inputs: { version: 6.x }
  - script: brew install bmake
    displayName: Install packages
  - script: bmake -j $(sysctl -n hw.ncpu)
    displayName: Build

- job: vs
  displayName: "Visual Studio"
  strategy:
    matrix:
      x64: { platform: x64 }
      x86: { platform: x86 }
      arm: { platform: ARM }
  pool:
    vmImage: windows-2022
  steps:
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: aoc.sln
      platform: $(platform)
      configuration: Release

- job: vc6
  displayName: "Visual C++ 6"
  continueOnError: true
  pool:
    name: default
    demands: vc6
  steps:
  - script: cd 2020\c\vc6 & msdev aoc2020.dsw /make all release
    displayName: Build 2020
  - script: cd 2022\c\vc6 & msdev aoc2022.dsw /make all release
    displayName: Build 2022
  - script: cd 2023\c\vc6 & msdev aoc2023.dsw /make all release
    displayName: Build 2023
