DAYS = day01 day02 day03

all:
	within $(DAYS) - $(MAKE)

clean:
	within $(DAYS) - $(MAKE) clean

check:
	within $(DAYS) - $(MAKE) check

solve:
	within $(DAYS) - $(MAKE) solve


.PHONY: all clean check solve
