CFLAGS += -Wall -Wextra
CFLAGS += -O2
CFLAGS += -DNDEBUG
CFLAGS += -g

LDFLAGS += -g

all: solve1 solve2 solve2-opt solve2-p solve2-plog

clean:
	rm -f solve1 solve2 solve2-opt solve2-p solve2-plog

.PHONY: all clean
