# day10 not yet ready
SUBDIRS=	day01 day02 day03 day04 day06 day07 day08 day08-cs \
		day08-fs intcode
TARGETS=	all clean

all:

all-day07: all-intcode

run:
	echo "'run' not implemented for 2019" >&2

.include "../subdirs.mk"
