CFLAGS  = /nologo /W3 /Zi

all: day14a.exe

clean:
	!del day14a.exe *.obj *.pdb *.ilk

day14a.exe: day14a.c khash.c khash.h
	$(CC) $(CFLAGS) $(LDFLAGS) day14a.c khash.c $(LDLIBS)

day14b.exe:
	@echo day14b uses variable-length arrays, unsupported by Visual C++

.PHONY: all clean
