jobs:

- job: linux
  displayName: Linux
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: cd 2020 && ../ci/az-make.sh -j
    displayName: Build
  - script: cd 2020/c && ./all.sh
    displayName: Run (C)
    failOnStderr: true

- job: linux_arm
  displayName: Linux (arm)
  pool:
    name: default
    demands:
    - agent.os -equals Linux
    - agent.osarchitecture -equals ARM
  steps:
  - script: cd 2020 && ../ci/az-make.sh -j c
    displayName: Build
  - script: cd 2020/c && ./all.sh
    displayName: Run (C)
    failOnStderr: true

- job: macos
  displayName: macOS
  pool:
    vmImage: macOS-10.15
  steps:
  - script: cd 2020 && ../ci/az-make.sh -j
    displayName: Build
  - script: cd 2020/c && ./all.sh
    displayName: Run (C)
    failOnStderr: true

- job: vc6
  displayName: Visual C++ 6
  pool:
    name: default
    demands: vc6
  steps:
  - script: cd 2020\c\vc6 & msdev aoc2020.dsw /make all release
    displayName: Build
  - script: cd 2020\c\vc6 & all.bat
    displayName: Run
