jobs:

- job: linux
  displayName: Linux
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: ci/az-make.sh -j
    displayName: Build
  - script: ci/az-make.sh -j run
    displayName: Run

- job: linux_arm
  displayName: Linux (arm)
  continueOnError: true
  pool:
    name: default
    demands:
    - agent.os -equals Linux
    - agent.osarchitecture -equals ARM
  steps:
  - script: ci/az-make.sh -j
    displayName: Build
  - script: ci/az-make.sh -j run
    displayName: Run

- job: macos
  displayName: macOS
  pool:
    vmImage: macOS-10.15
  steps:
  - script: ci/az-make.sh -j
    displayName: Build
  - script: ci/az-make.sh -j run
    displayName: Run

- job: vs_x86
  displayName: "2020: Visual Studio (x86)"
  pool:
    vmImage: windows-2019
  steps:
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: aoc.sln
      platform: x86
      configuration: Release
  - task: PowerShell@2
    displayName: Run (C)
    inputs:
      filePath: 2020/c/vs/all.ps1
      arguments: '"Win32 Release"'
      workingDirectory: 2020/c/vs/

- job: vs_x64
  displayName: "2020: Visual Studio (x64)"
  pool:
    vmImage: windows-2019
  steps:
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: aoc.sln
      platform: x64
      configuration: Release
  - task: PowerShell@2
    displayName: Run (C)
    inputs:
      filePath: 2020/c/vs/all.ps1
      arguments: '"x64 Release"'
      workingDirectory: 2020/c/vs/

- job: vs_arm
  displayName: "2020: Visual Studio (arm)"
  pool:
    vmImage: windows-2019
  steps:
  - task: VSBuild@1
    displayName: Build
    inputs:
      solution: aoc.sln
      platform: ARM
      configuration: Release

- job: vc6
  displayName: "2020: Visual C++ 6"
  continueOnError: true
  pool:
    name: default
    demands: vc6
  steps:
  - script: cd 2020\c\vc6 & msdev aoc2020.dsw /make all release
    displayName: Build
  - script: cd 2020\c\vc6 & all.bat
    displayName: Run
