jobs:

- job: linux
  displayName: Linux
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: cd 2020 && ../ci/az-make.sh -j
    displayName: Build
  - script: cd 2020/c && ./all.sh
    displayName: Run (C)
    failOnStderr: true

- job: linux_arm
  displayName: Linux (arm)
  continueOnError: true
  pool:
    name: default
    demands:
    - agent.os -equals Linux
    - agent.osarchitecture -equals ARM
  steps:
  - script: cd 2020 && ../ci/az-make.sh -j c
    displayName: Build
  - script: cd 2020/c && ./all.sh
    displayName: Run (C)
    failOnStderr: true

- job: macos
  displayName: macOS
  pool:
    vmImage: macOS-10.15
  steps:
  - script: cd 2020 && ../ci/az-make.sh -j
    displayName: Build
  - script: cd 2020/c && ./all.sh
    displayName: Run (C)
    failOnStderr: true

- job: vc_x86
  displayName: Visual C++ (x86)
  pool:
    vmImage: windows-2019
  steps:
  - task: VSBuild@1
    displayName: Build
    inputs:
      platform: x86
      configuration: Release
  - task: PowerShell@2
    displayName: Run (C)
    inputs:
      filePath: 2020/c/vs/all.ps1
      arguments: '"Win32 Release"'
      workingDirectory: 2020/c/vs/

- job: vc_x64
  displayName: Visual C++ (x64)
  pool:
    vmImage: windows-2019
  steps:
  - task: VSBuild@1
    displayName: Build
    inputs:
      platform: x64
      configuration: Release
  - task: PowerShell@2
    displayName: Run (C)
    inputs:
      filePath: 2020/c/vs/all.ps1
      arguments: '"x64 Release"'
      workingDirectory: 2020/c/vs/

- job: vc6
  displayName: Visual C++ 6
  continueOnError: true
  pool:
    name: default
    demands: vc6
  steps:
  - script: cd 2020\c\vc6 & msdev aoc2020.dsw /make all release
    displayName: Build
  - script: cd 2020\c\vc6 & all.bat
    displayName: Run
