jobs:
- job: Linux
  pool:
    vmImage: ubuntu-20.04
  steps:
  - script: cd 2020 && ../ci/az-make.sh -j
    displayName: Build
  - script: cd 2020/c && ./all.sh
    displayName: Run (C)
- job: macOS
  pool:
    vmImage: macOS-10.15
  steps:
  - script: cd 2020 && ../ci/az-make.sh -j
    displayName: Build
  - script: cd 2020/c && ./all.sh
    displayName: Run (C)
