on: push

jobs:
  linux:
    strategy:
      matrix:
        host: [ubuntu-20.04, ubuntu-24.04]  # oldest and latest
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y bmake mono-devel
    - run: bmake -j $(nproc)

  macos:
    strategy:
      matrix:
        host: [macos-13, macos-14]          # Intel and ARM
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v3
    - run: brew install bmake
    - run: bmake -j $(sysctl -n hw.ncpu)

  vs:
    strategy:
      matrix:
        platform: [x86, x64, ARM]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1.1
    - run: msbuild aoc.sln /p:Configuration=Release /p:Platform=${{ matrix.platform }}
