on: push

jobs:
  linux:
    strategy:
      matrix:
        host: [ubuntu-20.04, ubuntu-latest]  # oldest and latest
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y bmake
    - run: bmake -j $(nproc)

  macos:
    strategy:
      matrix:
        host: [macos-13, macos-latest]       # Intel and ARM
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v3
    - run: brew install bmake
    - run: bmake -j $(sysctl -n hw.ncpu)

  vs:
    strategy:
      matrix:
        platform:
        - x64
        #- x86   # broken due to missing v120 toolset
        #- ARM   # broken due to missing SDK
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1.1
    - run: msbuild aoc.sln /p:Platform=${{ matrix.platform }}
