on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y bmake
    - run: bmake

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: brew install bmake
    - run: bmake

  vs:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1.1
    - run: msbuild aoc.sln
